### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by bondra311** [amishne/llvm-ir-editor#88]
Hi 
I have problem with plugin installation into the newest eclipse. Look at the error dialog.

Best Regards,
Ondrej

![llvm_instalation](https://f.cloud.github.com/assets/5322409/1035798/45539d96-0f30-11e3-9c78-b35282cd8184.png)

**Comment by amishne** [comment]
Hi Ondrej,

Can you please try again? I've made an update that should make it work properly now.

**Comment by bondra311** [comment]
Hi Alon,
it works correctly now. Thanks.
Ondrej
